modLoader="javafml"
loaderVersion="[36,)"
license="AGPL v3.0"
[[mods]]
modId="realhomehuntforge"
version="${file.jarVersion}"
displayName="RealHomeHuntForge"
credits="Liangbai"
authors="Liangbai"
description='''
The mod for Bukkit RealHomeHuntPlugin
'''
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="SERVER"
