modLoader="javafml"
loaderVersion="[27,)"
license="AGPL v3.0"
[[mods]]
modId="realhomehuntforge"
version="${file.jarVersion}"
displayName="RealHomeHuntForge"
credits="Liangbai"
authors="Liangbai"
description='''
            The mod for Bukkit RealHomeHuntPlugin
            '''